### ISSUE TITLE
Edit ecosystems and select maps from which data would be drawn

### ISSUE THREAD

**Issue by jaydorsey** [rubyforgood/ghgvc#4]
Related to https://github.com/ebimodeling/ghgvc/issues/12

**Comment by teixeirak** [comment]
Actually, this is something else. I don't see the issue for it on the ebimodeling branch, but I'd be surprised if its not there.

Basically, we have lots of maps of ecosystem properties of relevance to calculating ecosystem climate services (biomass, soil carbon, etc.). We want to make it possible for users to go in to the edit ecosystems function and select to draw data from one of these maps rather than whatever happens to be the default.
