### ISSUE TITLE
Add tooltip to advanced settings

### ISSUE THREAD

**Issue by jaydorsey** [rubyforgood/ghgvc#60]
Add an icon next to the label for each of the advanced settings. Include a description of the settings

![image](https://user-images.githubusercontent.com/191564/27011913-6d457caa-4e94-11e7-8b9c-c52523c2fdd9.png)

Icons can be the simple `glyphicon-question-sign` or similar. No descriptions at present, but putting these in the `en.yml` might make it easier to switch them out later.

Related to #29

**Comment by teixeirak** [comment]
I'd like to add a few minor cleanup items here:
1- Switch the order of "years of analysis" and "years of emissions"
2- Reword the following:
-Years of emissions--> Years of ecosystem-climate exchange
-Decay rate--> Annual discount rate
-Sources--> Components
3-Add a check box below Greenhouse Gasses for "Biophysical components" (I think I saw that in an earlier screenshot, but it has disappeared in this one). This should be on the same level of organization as Greenhouse gasses (as opposed to appearing as if its in the same list as CO2, N2O, and CH4). There should be an icon associated with this one too.
4- Make the numbers in CO2, N2O, and CH4 subscripts.

**Comment by teixeirak** [comment]
A description for each of the settings is given below. If these descriptions are too long to fit, I can shorten them. 

*Years of ecosystem-climate exchange*- Because land use changes typically persist on time scales of decades to centuries, it is appropriate that the climate regulation services of ecosystems be assessed over a decadal time frame. This parameter controls the number of years over which ecosystem-climate interactions are assessed. We consider 50 years to be an appropriate default choice.
For a technical discussion of how ecosystem climate services vary with this parameter, see the following references:
Anderson-Teixeira KJ, DeLucia EH (2011) The greenhouse gas value of ecosystems. Global Change Biology, 17, 425–438.
Anderson-Teixeira KJ, Snyder PK, Twine TE, Cuadra SV, Costa MH, DeLucia EH (2012) Climate-regulation services of natural and agricultural ecoregions of the Americas. Nature Climate Change, 2, 177–181.

*Years of analysis*- Because greenhouse gasses remain in the atmosphere – and thereby impact the climate – for many years following their release, it may be desirable to evaluate the climate impact of ecosystem-atmosphere GHG exchange over a time frame that is longer that that over which ecosystem-atmosphere exchange of greenhouse gasses is assessed. We consider 50 years (or 100 years when biophysical effects are not included) to be an appropriate default choice. 
For a technical discussion of how ecosystem climate services vary with this parameter, see the following references:
Anderson-Teixeira KJ, DeLucia EH (2011) The greenhouse gas value of ecosystems. Global Change Biology, 17, 425–438.
Anderson-Teixeira KJ, Snyder PK, Twine TE, Cuadra SV, Costa MH, DeLucia EH (2012) Climate-regulation services of natural and agricultural ecoregions of the Americas. Nature Climate Change, 2, 177–181.

*Annual Discount Rate*- Applying an annual discount rate places greater weight on current than on future ecosystem-climate exchanges. When annual discount rate is zero, no weighting is applied; higher values place progressively less weight on later exchanges. Applying an annual discount rate may be desirable because (1) earlier exchanges may be more likely to determine the fate of climate change in that they could trigger feedback mechanisms or push the climate system past critical damage thresholds, and (2) society tends to place more value on near-term than on long-term costs and benefits, leading economic and policy applications to often apply an annual discount rate to future greenhouse gas emissions (typically, annual discount rate 0.10). As a default, we do not apply an annual discount rate (annual discount rate=0). 
For a technical discussion of how ecosystem climate services vary with this parameter, see the following reference:
Anderson-Teixeira KJ, DeLucia EH (2011) The greenhouse gas value of ecosystems. Global Change Biology, 17, 425–438.

*Greenhouse Gases*- The greenhouse gasses carbon dioxide (CO2), methane (CH4), and nitrous oxide (N2O) are exchanged between ecosystems and the atmosphere. While CO2 is generally the most important of these for unmanaged terrestrial ecosystems, CH4 and N2O can contribute significantly to an ecosystem’s greenhouse gas value, particularly for wetlands (CH4), fertilized croplands (N2O), and pasture (CH4 and N2O). User may select which to include. As a default, we recommend inclusion of all three.

For a technical discussion of how ecosystem climate services are shaped by greenhouse gases, see the following reference:
Anderson-Teixeira KJ, DeLucia EH (2011) The greenhouse gas value of ecosystems. Global Change Biology, 17, 425–438.


*Biophysical Components*- In addition to exchanging greenhouse gasses with the atmosphere, ecosystems also strongly influence the energy balance of the land surface. There is not yet scientific consensus as to the best method for integrating greenhouse gases and biophysical components into a single metric; the calculator applies one of several proposed metrics.  As a default, we recommend inclusion of biophysical components. However, we note that the calculator is currently able to compute biophysical effects for a subset of ecosystem types.

For a technical discussion of how ecosystem climate services are shaped by biophysical components, see the following reference:
Anderson-Teixeira KJ, Snyder PK, Twine TE, Cuadra SV, Costa MH, DeLucia EH (2012) Climate-regulation services of natural and agricultural ecoregions of the Americas. Nature Climate Change, 2, 177–181.

*Components*- Ecosystems contribute to climate regulation through storage of organic matter and ongoing ecosystem-atmosphere exchange.  Moreover, climate regulation values are reduced in ecosystems that are likely to undergo a major disturbance (for example, fire) within the time frame of interest. Users may select which of these components to include. As a default, we recommend inclusion of all, but note that default disturbance rates are currently set to zero and treatment of disturbance remains rudimentary. Disturbance can only be calculated if user edits disturbance-related parameters (for example, disturbance rate). 

For a technical discussion of how ecosystem climate services are shaped each of these components, see the following reference:
Anderson-Teixeira KJ, DeLucia EH (2011) The greenhouse gas value of ecosystems. Global Change Biology, 17, 425–438.

**Comment by jaydorsey** [comment]
@teixeirak Is Biophysical Components the same as one or more of the items in the screenshot below (Anthropogenic Effects and/or Biophysical Effects). The screenshot in this original ticket was an older one that didn't show these two additional fields

![image](https://user-images.githubusercontent.com/191564/27840640-a2553c0a-60c8-11e7-83e6-e6aac765601a.png)

**Comment by jaydorsey** [comment]
e.g. Is this closer to how the options are supposed to be grouped?

![image](https://user-images.githubusercontent.com/191564/27841073-4ed1aa7e-60cc-11e7-8233-ad8e43faf774.png)

**Comment by teixeirak** [comment]
Let's change the title of anthropogenic effects to "Associated anthropogenic emissions" and move that under the greenhouse gasses heading. Biophysical components should be its own heading on the level of Greenhouse Gases, but we currently have only one option (off or on). I think the best way to handle this is to keep the heading and change "biophysical effects" to "Net Radiation and Latent Cooling".

**Comment by teixeirak** [comment]
Here is the description for Associated anthropogenic emissions:

_Associated anthropogenic emissions_- In the case of agroecosystems, a complete greenhouse gas accounting must also include associated anthropogenic CO2 emissions, such as those from farm machinery (fuel combustion emissions) and those associated with agricultural inputs (for example, emissions from lime and fertilizer production).

For a technical discussion of how ecosystem climate services are shaped by associated anthropogenic emissions, see the following reference:
Anderson-Teixeira KJ, DeLucia EH (2011) The greenhouse gas value of ecosystems. Global Change Biology, 17, 425–438.
