### ISSUE TITLE
Cleanup empty controllers, routes, views, etc

### ISSUE THREAD

**Issue by jaydorsey** [rubyforgood/ghgvc#65]
There are a  number of controllers, routes, views, css, js, etc that appear to be scaffolded but are not actually used. Remove these.

**Comment by VictoriaVasys** [comment]
@jaydorsey, I looked into this & only found the following:

* User.rb has comments referring to information that can be found in schema (not sure if those should stay)
* StaticPagesController doesn't contain the about action although there is a route for it. Additional associated views are present, but no there are no routes or actions for any of them (I haven't used static pages before, so not sure if this is conventional/intentional)
* There are a few .keep files that can be deleted; I can make a PR deleting those along with any of the changes you'd like to see above.
